apiVersion: apps/v1
kind: Deployment
metadata:
  name: brainwave-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brainwave-deployment
  template:
    metadata:
      labels:
        app: brainwave-deployment
    spec:
      containers:
      - name: brainwave-deployment
        image: amuldark/brainwave:latest
        ports:
        - containerPort: 5173

--- 

apiVersion: v1
kind: Service
metadata:
  name: brainwave-service
spec:
  selector:
    app: brainwave-deployment
  ports:
  - protocol: TCP
    port: 5173
    targetPort: 80
  type: LoadBalancer